### ISSUE TITLE
Deprecated state "installed" used in task "Install aptitude"

### ISSUE THREAD

**Issue by WilliamCocker** [githubixx/ansible-role-harden-linux#2]
The state "installed" is deprecated and should be replaced by "present" in task "Install aptitude"

![screen shot 2018-05-04 at 16 48 55](https://user-images.githubusercontent.com/37018962/39636463-8cd5b4bc-4fc0-11e8-8180-8f2ef8bf1423.png)

I'm quite new at GitHub and Ansible, so for the time being I'd rather open an issue than submit a PR I would not be very confident with...

Thanks.

**Comment by githubixx** [comment]
Thanks for the hint! I already have this on my TODO list ;-) Will have a look next week.

**Comment by githubixx** [comment]
Fixed in https://github.com/githubixx/ansible-role-harden-linux/pull/3
